### ISSUE TITLE
Cannot start http server on non-default port

### ISSUE THREAD

**Issue by eliotmartin** [irvinlim/apple-health-ingester#2]
Hey - Trying to expose an influxdb backend on port 8083.  Getting the following...

```
time="2022-05-02T17:43:56Z" level=info msg="registered backend" backend=InfluxDB
time="2022-05-02T17:43:56Z" level=info msg="starting ingester"
time="2022-05-02T17:43:56Z" level=info msg="starting http server" listen_addr=8083
time="2022-05-02T17:43:56Z" level=panic msg="cannot start http server"
panic: (*logrus.Entry) 0xc00018a1c0
goroutine 21 [running]:
github.com/sirupsen/logrus.Entry.log({0xc0001147e0, 0xc0001880c0, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x2de
github.com/sirupsen/logrus.(*Entry).Log(0xc00018a000, 0x0, {0xc000098f10, 0x0, 0x0})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xa8
github.com/sirupsen/logrus.(*Entry).Logf(0xc00018a000, 0x0, {0x7b4fb4, 0x6162f8}, {0x0, 0x0, 0x7ffc92e5de88})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:333 +0x85
github.com/sirupsen/logrus.(*Logger).Logf(0xc0001147e0, 0x0, {0x7b4fb4, 0x18}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:146 +0x85
github.com/sirupsen/logrus.(*Logger).Panicf(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:187
github.com/sirupsen/logrus.Panicf(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:174
main.main.func1()
	/go/src/workspace/cmd/ingester/main.go:62 +0xe7
created by main.main
	/go/src/workspace/cmd/ingester/main.go:59 +0x3c5
```

**Comment by irvinlim** [comment]
Hey @eliotmartin, thanks for opening this!

The error is most likely due to some socket error, perhaps the port is already in use. Unfortunately I didn't log the error when this happens, but this should be now fixed and latest image pushed to Docker Hub.

Could you try to pull the latest image again, and if you still cannot figure out the error you can report back! Cheers

**Comment by irvinlim** [comment]
Actually I just noticed the issue. You need to use `:8083` instead of just `8083`, which means to listen on all interfaces at port 8083. Maybe you can try that!

**Comment by irvinlim** [comment]
I'll close the issue now, as it seems like it's a configuration issue :)
